### PR TITLE
Add CtkControl-getSynchronous. Change CtkScore:groupTogether allow for large numbers of buffers in a score.

### PR DESCRIPTION
**Pull request by mtmccrea**
Add getSynchronous method to CtkControl. Modify CtkScore:groupTogether to allow for large numbers of buffers in a score.

### CODE REVIEW

**Comment by crucialfelix** [comment]
@joshpar Could you check this out ? I forget if you are currently actively developing Ctk.

**Comment by joshpar** [comment]
@mtmccrea - why max events at a time of 30? Is this to try and prevent a message size from getting too big? If so, it would be better to figure out that max size, and build a way to add things until you get to tht size. If there is another reason, please let me know.

**Comment by mtmccrea** [comment]
@joshpar - This fix was for @joslloand for rendering scores that load hundreds of buffers (FIR kernels for processing HOA5 signals), so I've asked him to run his render again to record the Error dump and narrow in on a specific breaking point. I'll reply as soon as I hear back from him.
Thanks!

**Comment by joslloand** [comment]
@joshpar - I'm planning to sit down with and make a simple example that illustrates the issue. (Sorry to keep you waiting on this!)

While maybe not related, I have seen these issues in the SC3 base:
- supercollider/supercollider#1553
- supercollider/supercollider#61
- supercollider/supercollider#714

**Comment by mtmccrea** [comment]
@joshpar - I've submitted a new pull request in the meantime for the other fixes in this pull request, which excludes the groupTogether patch.

**Comment by joshpar** [comment]
@mtmccrea - sorry, finally getting around to this. Could you please look again at the pull request and see if it is still valid? Also - was there ever resolution on the remaining issues that @joslloand was seeing?

**Comment by joslloand** [comment]
Hi @joshpar,  @mtmccrea 

The machine where I was doing that work is still in a box after my move, so won't be easy to dig out in the short term....

**Comment by mtmccrea** [comment]
Hi @joshpar –
Yep, it's still a valid request. I removed the bit related to CtkScore rendering, we'll have to wait on Jo's testing for that. The remaining changes are minor: adding a CtkBus:getSynchronous as well as some Bus-like variable synonyms: -busnum, -index, and -numChannels. 

Thanks!

**Comment by mtmccrea** [comment]
@joshpar - ah, I see you already merged this through #4. So in that case this pull is no longer valid. Sorry for the confusion!

**Comment by joshpar** [comment]
@mtmccrea - I think this request is no longer valid. Can you please make sure and let me know if I can close it? Thanks!

**Comment by mtmccrea** [comment]
Hi @joshpar, I think we can close this given that some of the changes are already merged, and we don't know when we'll get around to finding a specific reproducer to determine a precise `maxEventsAtOneTime`.
I've stashed this fix in my extensions folder so we have it on hand, and I'll put in another PR when we narrow down that variable. (@joslloand )

**Pull request closed without merging**
